logLevel = "WARN"
defaultEntryPoints = ["http", "https"]

[api]

[entryPoints]

[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[acme]
email = "gustavo.mtborges@gmail.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
swarmmode = true
exposedbydefault = false
